### ISSUE TITLE
 1-aggregate-data.R file error

### ISSUE THREAD

**Issue by divya0singh** [seanangio/in_household#1]
After running the file '1-aggregate-data.R', I got this error:
Error: `path` does not exist: ‘1-raw-data/2001/s2_H - 12 Distribution of Households by Source and Location of Drinking Water and Availability of Electricity and Latrine Table For Andhra Pradesh.xlsx’.

Also, could not understand how the data is coming? I know that the data source is Census Digital Library and have even gone through the code.
if you could help me resolve this, it would be appreciated.
![error_file](https://user-images.githubusercontent.com/47349897/52265949-376a8000-295b-11e9-8a32-5ef6e3a62cd0.png)

**Comment by jitendrashahiitb** [comment]
If we can separate 1> the data preparation (including download, aggregating, cleaning etc) from 2> visualization and analysis , it will immensely help. The data frames (as output by first item and as input to next item) used may need to be described in detail ( unless that has been already done and I have not yet seen).

**Comment by divya0singh** [comment]
Error: `.x` is empty, and no `.init` supplied

After bypassing the portion of code(which created error as mentioned in the post), I tried to run the rest of the code and got this error: 
 Error: `.x` is empty, and no `.init` supplied 

![x_is_empty](https://user-images.githubusercontent.com/47349897/52268862-8962d400-2962-11e9-9a28-b4088344b93c.png)

**Comment by seanangio** [comment]
After finishing most of the data cleaning, I noticed a problem in the Andhra Pradesh file. The original Andhra Pradesh file, unlike every other file, was separated into 2 sheets in the same file. I corrected this locally, but this step may not be reproducible from the original script. But I believe that's the source of your problem.

**Comment by jitendrashahiitb** [comment]
So how do you propose we should proceed? 
Any help?

**Comment by seanangio** [comment]
If you're just concerned with this data, then you can manually add the second sheet of the Andhra Pradesh file as a separate file. Or paste the second sheet at the bottom of the first. A better solution if you're looking to apply this to other data, is to adjust the `read_raw()` function to check excel sheets for multiple sheets and read in those as well.
